use_frameworks!

platform :ios, '10.0'

target 'TLDownloadManager_Example' do
  pod 'TLDownloadManager', :path => '../'

  target 'TLDownloadManager_Tests' do
    inherit! :search_paths

    
  end
end
